import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/service/bike-service.jpg',
    title: 'Comprehensive Bike Servicing',
    rating: 5,
    ratingCount: 8,
    price: 499,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/service/car-diagnostics.jpg',
    title: 'Complete Car diagnostics',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/service/car-service.jpg',
    title: 'Complete Car service',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/service/re-paint.jpg',
    title: 'Paint job for your vehicle',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/service/tire-replace.jpg',
    title: 'Tire replacement and alignment',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  // {
  //   id: 6,
  //   cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
  //   title: 'Ethical Hacking Bootcamp Zero to Mastery',
  //   rating: 5,
  //   ratingCount: 14,
  //   price: 35,
  //   category: 'Beginner',
  // },
  // {
  //   id: 7,
  //   cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
  //   title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
  //   rating: 4,
  //   ratingCount: 6,
  //   price: 25,
  //   category: 'Beginner',
  // },
]
